### 1. 장바구니 담기 테스트 (POST)
POST http://localhost:8080/api/cart
Content-Type: application/json

{
  "studentId": "12345678",
  "courseId": 1
}

### 2. 장바구니 조회 테스트 (GET)
GET http://localhost:8080/api/cart/12345678